"""message

Revision ID: 80b32d8c0518
Revises: 98589907090c
Create Date: 2024-07-01 21:11:17.868067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b32d8c0518'
down_revision = '98589907090c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
